Don't warn when UCOH is on by default
openjdk/lilliput pull request #165
Opened 2024-04-24 05:23 UTC by stefank

When running testing with UCOH enabled by default in the code and non-generational ZGC the JVM prints this warning, which causes multiple failures in the testing. I'd like to propose that we  (at least temporarily) only write this warning if the user explicitly asked for UCOH.

2024-04-24 05:46 UTC, rkennke requested changes
Oh I believe this can be removed altogether. The reason why ZGC had problems was bad interaction/races with displaced headers, but with OMWorld this should no longer be the case.

2024-04-24 06:23 UTC, stefank commented
OK. Let me think about that a bit and I'll update the PR later.

2024-04-25 11:46 UTC, rkennke approved these changes
Looks good! Thanks!

2024-04-25 13:52 UTC, stefank commented
Thanks for reviewing!
/integrate

2024-04-25 13:53 UTC, closed without merging